#!/bin/bash
cwd=$(pwd)
if [[ `uname` == 'Linux' ]]; then
	for file in $cwd/configs/*; do
		ln -snfv `dirname $file/.` ~/.`basename $file`
	done
	cp --verbose -r $cwd/resources/fonts/* ~/.fonts/
else
	echo 'Operating system not supported'
fi
