#!/bin/bash
cwd=$(pwd)
for file in $cwd/home/*; do
    if [[ `basename $file` == 'config' ]]; then
        for file in $cwd/home/config/*; do
            ln -snfv $file ~/.config/`basename $file`
        done
    else
        ln -snfv $file ~/.`basename $file`
    fi
done
