#!/bin/bash
cwd=$(pwd)
if [[ `uname` == 'Linux' ]]; then
	for file in $cwd/configs/*; do
		ln -snfv `dirname $file/.` ~/.`basename $file`
	done
	for file in $cwd/resources/*; do
		ln -snfv `dirname $file/.` ~/.`basename $file`
	done
else
	echo 'Operating system not supported'
fi
