call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline', {'as':'airline'}
Plug 'dag/vim-fish'           , {'as':'fish'}
Plug 'tpope/vim-fugitive'     , {'as':'fugitive'}
Plug 'airblade/vim-gitgutter' , {'as':'gitgutter'}
Plug 'morhetz/gruvbox'        , {'as':'gruvbox'}
Plug 'edkolev/tmuxline.vim'   , {'as':'tmuxline'}
call plug#end()

let g:airline_powerline_fonts=1
let g:airline_theme='dark'

colorscheme gruvbox
set background=dark
set term=xterm-256color

filetype indent on
filetype plugin on
syntax enable

" WIP ===========================================================================================
set number
set relativenumber
set switchbuf=useopen

set autoindent
set colorcolumn=100
set nowrap
set ignorecase
set smartcase
set smartindent
set splitbelow
set splitright

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

"set timeout=1000
"set ttimeout=1000
"set timeoutlen=1000
set ttimeoutlen=100
set updatetime=100

" TENTATIVE
set ttymouse=xterm2
set backspace=2
set cursorline
set hlsearch
set incsearch
set laststatus=2
set mouse=a
set ruler
set showcmd
set wildmenu

highlight Normal                ctermbg=None
highlight SignColumn            ctermbg=None
highlight GitGutterAdd          ctermbg=None
highlight GitGutterDelete       ctermbg=None
highlight GitGutterChange       ctermbg=None
highlight GitGutterChangeDelete ctermbg=None
