call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline', {'as':'airline'}
Plug 'dag/vim-fish'           , {'as':'fish'}
Plug 'tpope/vim-fugitive'     , {'as':'fugitive'}
Plug 'mhinz/vim-signify'      , {'as':'signify'}
Plug 'morhetz/gruvbox'        , {'as':'gruvbox'}
Plug 'sheerun/vim-polyglot'   , {'as':'polyglot'}
Plug 'edkolev/tmuxline.vim'   , {'as':'tmuxline'}
call plug#end()

let g:airline_powerline_fonts = 1
let g:airline_theme = 'gruvbox'

let g:gruvbox_bold = 1
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_invert_selection = 0
let g:gruvbox_invert_signs = 0
let g:gruvbox_italic = 1
let g:gruvbox_sign_column = 'bg0'

let g:signify_sign_add = '▎'
let g:signify_sign_change = '▎'
let g:signify_sign_delete = '▎'
let g:signify_sign_delete_first_line = '🭭'

filetype indent on
filetype plugin on
syntax enable

colorscheme gruvbox
set background=dark
set term=xterm-256color
set termguicolors

set mouse=a
set number
set relativenumber
set showcmd
set wildmenu

set hlsearch
set ignorecase
set incsearch

" WIP ===========================================================================================
set switchbuf=useopen

set autoindent
set colorcolumn=100
set nowrap
set smartcase
set smartindent
set splitbelow
set splitright

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

"set timeout=1000
"set ttimeout=1000
"set timeoutlen=1000
set ttimeoutlen=100
set updatetime=10

" TENTATIVE
set ttymouse=xterm2
set backspace=2
set cursorline
set laststatus=2

highlight SignifySignAdd    guifg=green
highlight SignifySignChange guifg=orange
highlight SignifySignDelete guifg=red

nnoremap <silent><CR> :nohlsearch<CR><CR>
