call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline', {'as':'airline'}
Plug 'catppuccin/vim'         , {'as':'catppuccin'}
Plug 'dag/vim-fish'           , {'as':'fish'}
Plug 'tpope/vim-fugitive'     , {'as':'fugitive'}
Plug 'sheerun/vim-polyglot'   , {'as':'polyglot'}
Plug 'mhinz/vim-signify'      , {'as':'signify'}
Plug 'edkolev/tmuxline.vim'   , {'as':'tmuxline'}
Plug 'fatih/vim-go'           , {'as':'vim-go'}
call plug#end()

let g:airline_powerline_fonts = 1
let g:airline_theme = 'catppuccin_mocha'

let g:signify_sign_add = '▎'
let g:signify_sign_change = '▎'
let g:signify_sign_delete = '▎'
let g:signify_sign_delete_first_line = '🭭'

filetype indent on
filetype plugin on
syntax enable

colorscheme catppuccin_mocha
set background=dark
set term=xterm-256color
set termguicolors

set mouse=a
set number
" set relativenumber
set showcmd
set wildmenu

set hlsearch
set ignorecase
set incsearch
"set textwidth=100
set colorcolumn=100

" WIP ===========================================================================================
set switchbuf=useopen

set autoindent
set nowrap
set smartcase
set smartindent
set splitbelow
set splitright

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

"set timeout=1000
"set ttimeout=1000
"set timeoutlen=1000
set ttimeoutlen=100
set updatetime=10

" TENTATIVE
set ttymouse=xterm2
set backspace=2
set cursorline
set laststatus=2

highlight Normal            guibg=NONE ctermbg=NONE
highlight SignColumn        guibg=NONE ctermbg=NONE
highlight SignifySignAdd    guifg=green
highlight SignifySignChange guifg=orange
highlight SignifySignDelete guifg=red

nnoremap <silent><CR> :nohlsearch<CR><CR>
