eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2024-08-19 17:14:18
export PATH="$PATH:/Users/abdulmalek/.local/bin"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
