export TERM="xterm-256color"
export ZSH=$HOME/.oh-my-zsh/
ZSH_THEME=terminalparty
plugins=(git)
source $ZSH/oh-my-zsh.sh

alias groot='cd $(git rev-parse --show-toplevel)'
alias lag="la --group-directories-first"
alias lav="la -v"
alias mpvnv='mpv --no-video'
alias open='xdg-open'
alias rall='cd ~/Documents/repositories/'
alias rdot='cd ~/Documents/repositories/dot-files'
alias scon='find ~ -name "*.sync*"'
alias vimide='vim +NERDTree +wincmd\ w'
alias xclip='xclip -selection clipboard'

gsdel() {
	if [[ -z $1 ]]; then
		echo "Submodule name not provided"
	else
		gspath=$(git submodule status | awk '{ print $2 }' | grep $1 | head -1)
		git submodule deinit --force -- $gspath
		rm -rf .git/modules/$gspath
		git rm -rf $gspath
		git commit -am "gsdel: remove submodule $gspath"
	fi
}

gsup() {
	if [[ $(git submodule update --recursive --remote) ]]; then
		git commit -am "gsup: update submodules to upstream"
	fi
}

mlib() {
	if [[ $1 == "-append" ]]; then
		echo $2 >> ~/Music/tracking/research
		tail ~/Music/tracking/research
	else
		grep -i $1 ~/Music/tracking/*
	fi
}

pkgup() {
	sudo apt update
	sudo apt upgrade
	sudo apt full-upgrade
	sudo apt autoclean
	sudo apt autoremove --purge
	if [[ $1 == "-all" ]]; then
		omz update
		pip3 install --upgrade youtube-dl
		vim +PlugUpdate +PlugUpgrade +qa
	fi
}

vlib() {
	if [[ $1 == "-append" ]]; then
		echo $2 >> ~/Videos/tracking/research
		tail ~/Videos/tracking/research
	else
		grep -i $1 ~/Videos/tracking/*
	fi
}
