export ZSH=$HOME/.ohmyzsh
ZSH_THEME="terminalparty"
plugins=(git)
source $ZSH/oh-my-zsh.sh

alias benchshell='for i in $(seq 1 10); do /usr/bin/time $SHELL -i -c exit; done'
alias ckrs='tickrs'
alias dkf='docker logs --follow'
alias groot='cd $(git rev-parse --show-toplevel)'
alias lag='la --group-directories-first'
alias la='ls -la'
alias lav='la -v'
alias lofi='mpv --no-video --volume=50 https://youtu.be/jfKfPfyJRdk'
alias ls='ls -G'
alias mpvnv='mpv --no-video'
alias tick='ticker'
alias ttynor='ln -snfv ~/Documents/almk-dev/dot-files/home/alacritty-normal.yml ~/.alacritty.yml'
alias ttyret='ln -snfv ~/Documents/almk-dev/dot-files/home/alacritty-retina.yml ~/.alacritty.yml'
alias xclip='xclip -selection clipboard'

gren() {
    if [[ -z $2 ]]; then
        OLD_BRANCH=$(git branch --show-current)
        NEW_BRANCH=$1
    else
        OLD_BRANCH=$1
        NEW_BRANCH=$2
    fi
    git branch -m $OLD_BRANCH $NEW_BRANCH
    git push origin --delete $OLD_BRANCH
    git branch --unset-upstream $NEW_BRANCH
    git push origin $NEW_BRANCH
    git push --set-upstream origin $NEW_BRANCH
}

# go
export GOPATH=$HOME/.go
export PATH=$GOPATH/bin:$PATH

# rust
. "$HOME/.cargo/env"

# direnv
eval "$(direnv hook zsh)"

# gcp
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/abdulmalek/Documents/gcloud/path.zsh.inc' ]; then . '/Users/abdulmalek/Documents/gcloud/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/abdulmalek/Documents/gcloud/completion.zsh.inc' ]; then . '/Users/abdulmalek/Documents/gcloud/completion.zsh.inc'; fi

# ruby
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.3

# pnpm
export PNPM_HOME="/Users/abdulmalek/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
