execute pathogen#infect()
"call plug#begin('~/.vim/plugged')
"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
"Plug 'ryanoasis/vim-devicons'
    "Plug 'vim-gitgutter'
"Plug 'vim-gruvbox'
"Plug 'scrooloose/nerdtree'
"Plug 'xuyuanp/nerdtree-git-plugin'
"Plug 'vim-supertab'
"Plug 'vim-tmuxline'
"call plug#end()

"let g:airline#extensions#tabline#formatter='unique_tail'
"let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#tabline#tab_nr_type = 1
"let g:airline#extensions#tabline#buffer_nr_show = 1

" FINAL
"
let g:airline_powerline_fonts=1
let g:airline_theme='powerlineish'
let g:DevIconsEnableFoldersOpenClose=1
let g:NERDTreeMinimalUI=1
let g:WebDevIconsUnicodeDecorateFolderNodes=1

colorscheme gruvbox
filetype indent on
filetype plugin on
syntax enable

map <space> :

" FINAL
set autoindent
set background=dark
set expandtab
set nowrap
set number
set smartindent
set splitbelow
set splitright
set term=xterm-256color
set textwidth=100
set ttimeoutlen=25
set updatetime=25

" TENTATIVE
set backspace=2
set colorcolumn=+1
set cursorline
set hlsearch
set incsearch
set laststatus=2
set mouse=a
set ruler
set showcmd
set wildmenu
set shiftwidth=4
set softtabstop=4
set tabstop=4

" DISCARD
" set showbreak=↳\

" highlight ColorColumn			ctermbg=DarkRed
highlight Normal				ctermbg=None
highlight SignColumn			ctermbg=None

highlight GitGutterAdd			ctermbg=None
highlight GitGutterDelete		ctermbg=None
highlight GitGutterChange		ctermbg=None
highlight GitGutterChangeDelete ctermbg=None
