call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'edkolev/tmuxline.vim',{'as':'tmuxline'}
Plug 'vim-airline/vim-airline',{'as':'airline'}
Plug 'vim-airline/vim-airline-themes',{'as':'airline-themes'}
Plug 'ryanoasis/vim-devicons',{'as':'devicons'}
Plug 'airblade/vim-gitgutter',{'as':'gitgutter'}
call plug#end()

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#formatter='unique_tail'
"let g:airline#extensions#tabline#tab_nr_type = 1
"let g:airline#extensions#tabline#buffer_nr_show = 1

let g:airline_powerline_fonts=1
let g:airline_theme='powerlineish'
let g:NERDTreeMinimalUI=1
let g:WebDevIconsNerdTreeAfterGlyphPadding='  '
let g:WebDevIconsUnicodeDecorateFolderNodes=1

colorscheme gruvbox
set background=dark
set term=xterm-256color

filetype indent on
filetype plugin on
syntax enable


" FINAL
set autoindent
set noexpandtab " important to decide later
set nowrap
set number
set smartindent
set splitbelow
set splitright
set textwidth=100
set ttimeoutlen=25
set updatetime=25

" TENTATIVE
set backspace=2
set colorcolumn=+1
set cursorline
set hlsearch
set incsearch
set laststatus=2
set mouse=a
set ruler
set showcmd
set wildmenu
set shiftwidth=4
set softtabstop=4
set tabstop=4

noremap <space> :

highlight Normal				ctermbg=None
highlight SignColumn			ctermbg=None
highlight GitGutterAdd			ctermbg=None
highlight GitGutterDelete		ctermbg=None
highlight GitGutterChange		ctermbg=None
highlight GitGutterChangeDelete ctermbg=None
