export TERM="xterm-256color"
export ZSH=$HOME/.oh-my-zsh/
ZSH_THEME="terminalparty"
plugins=(git)
source $ZSH/oh-my-zsh.sh

alias escmap='setxkbmap -option caps:escape'
alias groot='cd $(git rev-parse --show-toplevel)'
alias opn='xdg-open'
alias rall='cd ~/Documents/repos/'
alias rsys='cd ~/Documents/repos/system/'
alias vimide='vim -c "NERDTree | wincmd w"'
alias xclip='xclip -selection clipboard'
#alias mgrep, vgrep=

gsup() {
	if [[ $(git submodule update --recursive --remote) ]]; then
		git commit -am "UPDATE all submodules to upstream commits"
	fi
}

otbkup() {
	if [[ $1 == "-c"* ]]; then
		xclip -selection clipboard < ~/Documents/onetab-backup
	else
		xclip -selection clipboard -out > ~/Documents/onetab-backup
	fi
}

pkgup() {
	if [[ `uname` == "Linux" ]]; then
		if [[ -z $1 ]]; then
			sudo apt update
			sudo apt upgrade
			sudo apt autoclean
			sudo apt autoremove
			sudo apt dist-upgrade
			sudo snap refresh
			sudo pip3 install youtube-dl --upgrade
		fi
	else
		echo "Operating system not supported"
	fi
}

tland() {
	tmux split-window -h -p 40
	tmux split-window -v -p 70
	tmux split-window -v -p 70
	tmux send-keys -t 0.0 "vim -c q; clear" C-m
	tmux send-keys -t 0.1 "htop -d 10" C-m
	tmux send-keys -t 0.2 "vis" C-m
	tmux send-keys -t 0.3 "cmus" C-m
	tmux select-pane -t 0
}

tport() {
	tmux split-window -v -p 80
	tmux new-window
	tmux split-window -v -p 80
	tmux send-keys -t 0.0 "htop -d 10" C-m
	tmux send-keys -t 0.1 "vim -c q; clear" C-m
	tmux send-keys -t 1.0 "vis" C-m
	tmux send-keys -t 1.1 "cmus" C-m
	tmux select-window -t 0
	tmux select-pane -t 1
}
