export TERM="xterm-256color"
export ZSH=$HOME/.oh-my-zsh/
ZSH_THEME="terminalparty"
plugins=(git)
source $ZSH/oh-my-zsh.sh

#check for collisions for all
alias escmap='setxkbmap -option caps:escape'
alias groot='cd $(git rev-parse --show-toplevel)'
alias open='xdg-open'
alias rpos='cd ~/Documents/repos/'
alias rdot='cd ~/Documents/repos/dot-files'
alias vimide='vim -c "NERDTree | wincmd w"'
alias xclip='xclip -selection clipboard'
#alias mgrep, vgrep=

gsup() {
	if [[ $(git submodule update --recursive --remote) ]]; then
		git commit -am "UPDATE all submodules to upstream commits"
	fi
}

otbkup() {
	if [[ $1 == "-copy" ]]; then
		xclip -selection clipboard < ~/Documents/stash/onetab-backup
	else
		xclip -selection clipboard -out > ~/Documents/stash/onetab-backup
	fi
}

pkgup() {
	if [[ `uname` == "Linux" ]]; then
		if [[ -z $1 ]]; then
			sudo apt update
			sudo apt upgrade
			sudo apt autoclean
			sudo apt autoremove
			sudo apt dist-upgrade
			sudo snap refresh
			pipdate3
		fi
		if [[ $@ == *"-apt"* ]]; then
			sudo apt update
			sudo apt upgrade
			sudo apt autoclean
			sudo apt autoremove
		fi
		if [[ $@ == *"-dist"* ]]; then
			sudo apt dist-upgrade
		fi
		if [[ $1 == *"-snap"* ]]; then
			sudo snap refresh
		fi
		if [[ $@ == *"-pip"* ]]; then
			pipdate3
		fi
	else
		echo "Operating system not supported"
	fi
}

tland() {
	tmux split-window -h -p 40
	tmux split-window -v -p 70
	tmux split-window -v -p 70
	tmux send-keys -t 0.0 "vim -c q; clear" C-m
	tmux send-keys -t 0.1 "htop -d 5" C-m
	tmux send-keys -t 0.2 "vis" C-m
	tmux send-keys -t 0.3 "cmus" C-m
	tmux select-pane -t 0
}

tport() {
	tmux split-window -v -p 80
	tmux new-window
	tmux split-window -v
	tmux resize-pane -t 1.0 -y 8
	tmux send-keys -t 0.0 "vis" C-m
	tmux send-keys -t 0.1 "cmus" C-m
	tmux send-keys -t 1.0 "htop -d 10" C-m
	tmux send-keys -t 1.1 "vim -c q; clear" C-m
}
