export TERM="xterm-256color"
export ZSH=$HOME/.oh-my-zsh/
ZSH_THEME="terminalparty"
plugins=(git)
source $ZSH/oh-my-zsh.sh

alias escmap='setxkbmap -option caps:escape'
alias groot='cd $(git rev-parse --show-toplevel)'
alias open='xdg-open'
alias rall='cd ~/Documents/repos/'
alias rdot='cd ~/Documents/repos/dot-files'
alias vim='escmap; vim'
alias vimide='escmap; vim -c "NERDTree | wincmd w"'
alias xclip='xclip -selection clipboard'

grepm() { grep $1 ~/Music/tracking/* }
grepv() { grep $1 ~/Videos/tracking/* }

gsup() {
	if [[ $(git submodule update --recursive --remote) ]]; then
		git commit -am "Update all submodules to upstream commits"
	fi
}

otbkup() {
	if [[ $1 == "-copy" ]]; then
		xclip -selection clipboard < ~/Documents/stash/onetab-backup
	else
		xclip -selection clipboard -out > ~/Documents/stash/onetab-backup
		awk "NF" ~/Documents/stash/onetab-backup > onetab-backup-temp
		mv onetab-backup-temp ~/Documents/stash/onetab-backup
	fi
	head -5 ~/Documents/stash/onetab-backup
}

pkgup() {
	if [[ `uname` == "Linux" ]]; then
		sudo apt update
		sudo apt upgrade
		sudo apt autoclean
		sudo apt autoremove
		sudo apt dist-upgrade
		sudo snap refresh
		pip3 install --upgrade youtube_dl
	else
		echo "Operating system not supported"
	fi
}

tland() {
	if [[ $1 == "-right" ]]; then
		tmux split-window -t 0.0 -h -p 40
		tmux split-window -t 0.1 -v -p 70
		tmux split-window -t 0.2 -v -p 70
		tmux send-keys -t 0.0 "vim -c q; reset" C-m
		tmux send-keys -t 0.1 "htop -d 5" C-m
		tmux send-keys -t 0.2 "vis" C-m
		tmux send-keys -t 0.3 "cmus" C-m
		tmux select-pane -t 0
	else
		tmux split-window -t 0.0 -h -p 60
		tmux split-window -t 0.0 -v -p 70
		tmux split-window -t 0.1 -v -p 70
		tmux send-keys -t 0.0 "htop -d 5" C-m
		tmux send-keys -t 0.1 "vis" C-m
		tmux send-keys -t 0.2 "cmus" C-m
		tmux send-keys -t 0.3 "vim -c q; reset" C-m
		tmux select-pane -t 3
	fi
}

tport() {
	tmux split-window -t 0.0 -v -p 80
	tmux new-window
	tmux split-window -t 1.0 -v
	tmux resize-pane -t 1.0 -y 8
	tmux send-keys -t 0.0 "vis" C-m
	tmux send-keys -t 0.1 "cmus" C-m
	tmux send-keys -t 1.0 "htop -d 5" C-m
	tmux send-keys -t 1.1 "vim -c q; reset" C-m
}
